import { AlarmSeverity, AlarmStatus } from './alarm.entity';

/** Initial demo rows when `alarms` is empty (local / first boot). */
export const ALARM_SEED_FIXTURES: Array<{
  ref_code: string;
  title: string;
  description: string | null;
  severity: AlarmSeverity;
  category: string;
  list_meta: string;
  list_footer: string;
  assigned_to: string;
  detail_meta: string | null;
  recommended_action: string | null;
  is_read: boolean;
  status: AlarmStatus;
}> = [
  {
    ref_code: 'AL-012',
    title: 'Ramkishan Yadav — Driving Licence Expiring (5 days)',
    description: null,
    severity: AlarmSeverity.CRITICAL,
    category: 'COMPLIANCE',
    list_meta: 'DR-ST-00029 · Deployed · Vasant Kunj · Client: Suresh Agarwal',
    list_footer: 'Today 09:00 AM · DL expiry cron',
    assigned_to: 'Compliance',
    detail_meta: null,
    recommended_action: null,
    is_read: false,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-011',
    title: 'Client escalation — delayed replacement (Series DRIVER)',
    description: null,
    severity: AlarmSeverity.CRITICAL,
    category: 'CLIENT',
    list_meta: 'CL-4412 · Active contract · Gurgaon · Client: Meera Khanna',
    list_footer: 'Today 08:12 AM · SLA breach monitor',
    assigned_to: 'Ops Manager',
    detail_meta: null,
    recommended_action: null,
    is_read: false,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-010',
    title: 'Razorpay payout stuck > 48h — staff ST-2388',
    description: null,
    severity: AlarmSeverity.CRITICAL,
    category: 'PAYMENT',
    list_meta: 'PAY-9021 · Payroll batch #44 · NEFT pending',
    list_footer: 'Yesterday 11:40 PM · Finance webhook',
    assigned_to: 'Finance Team',
    detail_meta: null,
    recommended_action: null,
    is_read: false,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-009',
    title: 'Agarwal Family — Staff Abandonment Complaint',
    description:
      'Client Rekha Agarwal called at 11:15 AM to report Sudha Tiwari did not report for duty without any prior notice. This is the second such incident in 30 days. Client is threatening to cancel the agreement and demand replacement. Sudha Tiwari is unreachable on mobile.',
    severity: AlarmSeverity.HIGH,
    category: 'CLIENT',
    list_meta: 'CL-505 · Series MAID · South Ext · Client: R. Malhotra',
    list_footer: 'Yesterday 04:30 PM · RM hotline',
    assigned_to: 'RM West',
    detail_meta: 'SC-ST-00027 · Sudha Tiwari · Deployed 5 months · Greater Kailash-II, New Delhi',
    recommended_action:
      'Contact Sudha Tiwari immediately. If unreachable within 2 hours, initiate Placement Exit (scenario SC-09: client-initiated exit). Arrange replacement caretaker from pool within 72 hours per SLA. Document incident in shift log as ABSENT.',
    is_read: false,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-008',
    title: 'Sudha Tiwari — Police Verification Renewal Due',
    description:
      'Annual police verification for deployed staff Sudha Tiwari is past the 12-month renewal window. Client household agreement requires valid PV on file.',
    severity: AlarmSeverity.HIGH,
    category: 'COMPLIANCE',
    list_meta: 'DR-ST-00102 · Pre-deploy · Noida sector 62',
    list_footer: 'Yesterday 02:00 PM · Onboarding checklist',
    assigned_to: 'HR Manager',
    detail_meta: 'SC-ST-00027 · Deployed 5 months · PV dated 28 Apr 2025 (12 months old)',
    recommended_action:
      'Schedule PV renewal with the nearest police station or empanelled vendor within 7 days. Upload scanned receipt to compliance vault and mark checklist item PV-RENEW as complete.',
    is_read: true,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-007',
    title: 'SMS delivery failures spiking (12% last hour)',
    description: null,
    severity: AlarmSeverity.HIGH,
    category: 'SYSTEM',
    list_meta: 'INFRA-SMS · Provider: MSG91 · Region DEL',
    list_footer: 'Yesterday 12:15 PM · Monitoring',
    assigned_to: 'System Admin',
    detail_meta: null,
    recommended_action: null,
    is_read: false,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-006',
    title: 'Service quality follow-up — week 2 check-in',
    description: null,
    severity: AlarmSeverity.MEDIUM,
    category: 'CLIENT',
    list_meta: 'CL-3891 · Cook series · Defence Colony',
    list_footer: 'Yesterday 10:00 AM · CS playbook',
    assigned_to: 'CS Lead',
    detail_meta: null,
    recommended_action: null,
    is_read: true,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-005',
    title: 'Aadhaar masked mismatch — manual review queue',
    description: null,
    severity: AlarmSeverity.MEDIUM,
    category: 'COMPLIANCE',
    list_meta: 'ST-2401 · Verification · NSDL delta',
    list_footer: '13 May 06:20 PM · Compliance engine',
    assigned_to: 'Compliance',
    detail_meta: null,
    recommended_action: null,
    is_read: true,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-004',
    title: 'Contract renewal reminder — 7 days to expiry',
    description: null,
    severity: AlarmSeverity.MEDIUM,
    category: 'CLIENT',
    list_meta: 'CL-2209 · Driver · Client: Anil Kapoor',
    list_footer: '13 May 09:00 AM · Renewals cron',
    assigned_to: 'BM Delhi',
    detail_meta: null,
    recommended_action: null,
    is_read: false,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-003',
    title: 'Client invoice overdue — 9 days past due',
    description: null,
    severity: AlarmSeverity.MEDIUM,
    category: 'PAYMENT',
    list_meta: 'INV-7781 · Corporate · Rs 42,600',
    list_footer: '12 May 03:00 PM · AR aging',
    assigned_to: 'Finance Team',
    detail_meta: null,
    recommended_action: null,
    is_read: true,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-002',
    title: 'SMS quota at 85% for current billing cycle',
    description: null,
    severity: AlarmSeverity.LOW,
    category: 'SYSTEM',
    list_meta: 'INFRA-SMS · SendGrid / MSG91 blend',
    list_footer: '12 May 08:00 AM · Usage report',
    assigned_to: 'System Admin',
    detail_meta: null,
    recommended_action: null,
    is_read: true,
    status: AlarmStatus.OPEN,
  },
  {
    ref_code: 'AL-001',
    title: 'Feedback survey NPS dip — branch aggregate 6.2',
    description: null,
    severity: AlarmSeverity.LOW,
    category: 'CLIENT',
    list_meta: 'DEL-NCR · Rolling 30d · 38 responses',
    list_footer: '11 May 05:00 PM · CX dashboard',
    assigned_to: 'BM Delhi',
    detail_meta: null,
    recommended_action: null,
    is_read: true,
    status: AlarmStatus.OPEN,
  },
];
